### ISSUE TITLE
本地运行不稳定

### ISSUE THREAD

**Issue by XBisATrouble** [se4/get-back-cet#1]
经常会查询不到返回code=-1

**Comment by se4** [comment]
部分省份(例如安徽)不支持查询，查不到就返回错误。查询部分没几行，简单得令人发指，应该不会有错。

推荐使用CET APP对查不到的同学进行复查，如果CET APP能查到而cet_query.py查不到，那就说明脚本有缺陷了。

也可以使用Postman对查不到准考证的同学进行复查以确定是程序问题还是接口问题。
